# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-10 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_replace_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.IntegerField(choices=[(0, 'email'), (1, 'online')], verbose_name='medium'),
        ),
    ]
