# Generated by Django 2.1.3 on 2018-11-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180208_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.IntegerField(choices=[(0, 'email'), (1, 'online'), (2, 'slack')], verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='noticetype',
            name='label',
            field=models.CharField(max_length=40, unique=True, verbose_name='label'),
        ),
    ]
